function poll=getPoll(in_whitegrid)
poll=uint8(in_whitegrid(1:end-1,1:end-1,1:end-1))...
        +uint8(in_whitegrid(2:end,1:end-1,1:end-1))...
        +uint8(in_whitegrid(2:end,1:end-1,2:end))...
        +uint8(in_whitegrid(1:end-1,2:end,1:end-1))...
        +uint8(in_whitegrid(1:end-1,2:end,2:end))...
        +uint8(in_whitegrid(1:end-1,1:end-1,2:end))...
        +uint8(in_whitegrid(2:end,2:end,1:end-1))...
        +uint8(in_whitegrid(2:end,2:end,2:end));
